### ISSUE TITLE
When I increase the font size, the bottom part of terminal is slightly cut off (cosmetic issue)

### ISSUE THREAD

**Issue by prograhammer** [warpdotdev/blog-warpdotdev#1]
Problem:
When I increase the font size, the bottom part of terminal is slightly cut off (very close to bottom edge of screen).

Steps to Reproduce:
1. Go to Settings > Appearance
2. Change the font size to something higher than 13. I tried 18. (or increase font size using cmd + plus sign)
3. Run a command. I tried `npm i`.
4. Notice the bottom part of the command's output is slightly cutoff or there is no padding at all in the terminal below.

![image](https://user-images.githubusercontent.com/4474660/167011408-9600cfbf-1475-4f10-96ad-3a556b2b088c.png)

**Comment by elviskahoro** [comment]
@prograhammer can you post this issue in our main repo:
https://github.com/warpdotdev/Warp/issues
